improved recursive function

diff --git a/snapshot b/snapshot
--- a/snapshot
+++ b/snapshot
@@ -32,7 +32,7 @@ function usage {
 
 # Command-line argument checks.
 args=$(getopt -o ds: --long delete,subdirectory: -- "$@")
-if [ $? -ne 0 ]; then
+if [[ $? -ne 0 ]]; then
     usage
 fi
 
@@ -47,36 +47,36 @@ for true; do
     esac
 done
 
-if [ $delete == 1 ]; then
-    if [ $# -eq 0 ]; then
+if [[ $delete == 1 ]]; then
+    if [[ $# -eq 0 ]]; then
         usage
     fi
-elif [ $# -gt 1 ]; then
+elif [[ $# -gt 1 ]]; then
     usage
 fi
 
-if [ -n "$subdir" ] && [ $(basename "$subdir") != "$subdir" ]; then
+if [[ -n "$subdir" ]] && [[ $(basename "$subdir") != "$subdir" ]]; then
     echo "Invalid subdirectory: \"$subdir\" must not include directory." >&2
     exit 1
 fi
 
 # Filesystem checks.
 fs=$(stat -f -c %T $HOME)
-if [ $fs == ecryptfs ]; then
+if [[ $fs == ecryptfs ]]; then
     ENC_HOME=$(dirname $HOME)/.ecryptfs/$USER/.Private
     fs=$(stat -f -c %T $ENC_HOME)
-    if [ $fs != btrfs ]; then
+    if [[ $fs != btrfs ]]; then
         echo "Wrong filesystem: home directory is ecryptfs on $fs, not btrfs."\
              >&2
         exit 1
-    elif [ $(stat -c %i $ENC_HOME) -ne 256 ]; then
+    elif [[ $(stat -c %i $ENC_HOME) -ne 256 ]]; then
         echo "Not a subvolume: $ENC_HOME is not a btrfs subvolume." >&2
         exit 1
     fi
-elif [ $fs != btrfs ]; then
+elif [[ $fs != btrfs ]]; then
     echo "Wrong filesystem: home directory is on $fs, not btrfs." >&2
     exit 1
-elif [ $(stat -c %i $HOME) -ne 256 ]; then
+elif [[ $(stat -c %i $HOME) -ne 256 ]]; then
     echo "Not a subvolume: home directory is not a btrfs subvolume." >&2
     exit 1
 fi
@@ -84,41 +84,52 @@ fi
 SNAPSHOTS=$HOME/.snapshots
 MODE=700 # mode for snapshots
 
-function encrypted_path { # recursive function, parameter: $1 = decrypted path
-    if [ "$1" == "$HOME" ]; then
-        echo "$ENC_HOME"
+enc_path=
+function encrypted_path {
+    # recursive function, parameter: $1 = decrypted path
+    # result assigned to enc_path (not returned via echo)
+    if [[ "$1" == "$HOME" ]]; then
+        enc_path="$ENC_HOME"
     else
-        enc_dir=$(encrypted_path $(dirname "$1"))
-        inode=$(stat -c %i "$1")
-        if [ $inode -eq 256 ]; then
-            echo "Error: snapshot parent $1 cannot be a subvolume." >&2
-            exit 1
+        if encrypted_path $(dirname "$1"); then
+            enc_dir="$enc_path"
+            inode=$(stat -c %i "$1")
+            if [[ $inode -eq 256 ]]; then
+                echo "Error: snapshot parent $1 cannot be a subvolume." >&2
+                enc_path=
+                return 1
+            fi
+            enc_path=$(find "$enc_dir" -mindepth 1 -maxdepth 1 \
+                            -inum $inode -print)
+        else
+            return 1
         fi
-        find "$enc_dir" -mindepth 1 -maxdepth 1 -inum $inode -print
     fi
 }
 
-if [ $delete == 0 ]; then
+if [[ $delete == 0 ]]; then
+    #
     # create snapshot
-    if [ $# -eq 1 ] && [ $(basename "$1") != "$1" ]; then
+    #
+    if [[ $# -eq 1 ]] && [[ $(basename "$1") != "$1" ]]; then
         echo "Invalid snapshot: name $1 cannot include directory." >&2
         exit 1
     fi
 
     # Create directory ~/.snapshots if it does not already exist.
-    if [ ! -d $SNAPSHOTS ]; then
+    if [[ ! -d $SNAPSHOTS ]]; then
         mkdir --mode $MODE $SNAPSHOTS
     fi
 
     SNAPSHOT_PATH=$SNAPSHOTS
-    if [ -n "$subdir" ]; then
+    if [[ -n "$subdir" ]]; then
         SNAPSHOT_PATH=$SNAPSHOTS/"$subdir"
-        if [ ! -d "$SNAPSHOT_PATH" ]; then
+        if [[ ! -d "$SNAPSHOT_PATH" ]]; then
             mkdir --mode $MODE "$SNAPSHOT_PATH"
         fi
     fi
 
-    if [ $# -eq 0 ]; then
+    if [[ $# -eq 0 ]]; then
         SNAPSHOT_PATH=$SNAPSHOT_PATH/$(date +"%Y-%m-%d_%H:%M:%S")
     else
         SNAPSHOT_PATH=$SNAPSHOT_PATH/"$1"
@@ -127,51 +138,64 @@ if [ $delete == 0 ]; then
     #
     # Make sure that snapshot does not exist already.
     #
-    if [ -x "$SNAPSHOT_PATH" ]; then
+    if [[ -x "$SNAPSHOT_PATH" ]]; then
         echo "Error: snapshot $SNAPSHOT_PATH already exists." >&2
         exit 1
     fi
 
-    if [ ! -z ${ENC_HOME+x} ]; then
+    if [[ ! -z ${ENC_HOME+x} ]]; then
         # create temporary directory to look up its encrypted name
         mkdir --mode $MODE "$SNAPSHOT_PATH"
-        ENC_SNAPSHOT_PATH=$(encrypted_path "$SNAPSHOT_PATH")
-        rmdir "$SNAPSHOT_PATH"
+        if encrypted_path "$SNAPSHOT_PATH"; then
+            ENC_SNAPSHOT_PATH="$enc_path"
+            rmdir "$SNAPSHOT_PATH"
 
-        # create read-only snapshot
-        btrfs subvolume snapshot -r $ENC_HOME $ENC_SNAPSHOT_PATH > /dev/null &&\
-            echo "Created snapshot $SNAPSHOT_PATH."
+            # create read-only snapshot
+            btrfs subvolume snapshot -r $ENC_HOME $ENC_SNAPSHOT_PATH \
+                  > /dev/null && echo "Created snapshot $SNAPSHOT_PATH."
+        else
+            rmdir "$SNAPSHOT_PATH"
+            exit 1
+        fi
     else
         btrfs subvolume snapshot -r $HOME "$SNAPSHOT_PATH" > /dev/null && \
             echo "Created snapshot $SNAPSHOT_PATH."
     fi
 else
+    #
     # delete snapshots
+    #
     for snapshot in $*; do
-        if [ $(basename "$snapshot") != "$snapshot" ]; then
+        if [[ $(basename "$snapshot") != "$snapshot" ]]; then
             echo "Invalid snapshot: name $snapshot cannot include"\
                  "directory." >&2
             exit 1
         fi
         SNAPSHOT_PATH=$SNAPSHOTS
-        if [ -n "$subdir" ]; then
+        if [[ -n "$subdir" ]]; then
             SNAPSHOT_PATH=$SNAPSHOTS/$subdir
         fi
         SNAPSHOT_PATH=$SNAPSHOT_PATH/"$snapshot"
-        if [ ! -d "$SNAPSHOT_PATH" ]; then
+        if [[ ! -d "$SNAPSHOT_PATH" ]]; then
             echo "Not found: $SNAPSHOT_PATH does not exist." >&2
             exit 1
-        elif [ $(stat -c %i "$SNAPSHOT_PATH") -ne 256 ]; then
+        elif [[ $(stat -c %i "$SNAPSHOT_PATH") -ne 256 ]]; then
             echo "Not a snapshot: $SNAPSHOT_PATH is not a btrfs subvolume." >&2
             exit 1
-        elif [ ! -z ${ENC_HOME+x} ]; then
+        elif [[ ! -z ${ENC_HOME+x} ]]; then
             mv "$SNAPSHOT_PATH" "$SNAPSHOT_PATH".renamed
             mkdir --mode $MODE "$SNAPSHOT_PATH"
-            ENC_SNAPSHOT_PATH=$(encrypted_path "$SNAPSHOT_PATH")
-            rmdir "$SNAPSHOT_PATH"
-            mv "$SNAPSHOT_PATH".renamed "$SNAPSHOT_PATH"
-            sudo btrfs subvolume delete -c $ENC_SNAPSHOT_PATH > /dev/null && \
-                echo "Snapshot $SNAPSHOT_PATH deleted."
+            if encrypted_path "$SNAPSHOT_PATH"; then
+                ENC_SNAPSHOT_PATH="$enc_path"
+                rmdir "$SNAPSHOT_PATH"
+                mv "$SNAPSHOT_PATH".renamed "$SNAPSHOT_PATH"
+                sudo btrfs subvolume delete -c $ENC_SNAPSHOT_PATH \
+                     > /dev/null && echo "Snapshot $SNAPSHOT_PATH deleted."
+            else
+                rmdir "$SNAPSHOT_PATH"
+                mv "$SNAPSHOT_PATH".renamed "$SNAPSHOT_PATH"
+                exit 1
+            fi
         else
             sudo btrfs subvolume delete -c "$SNAPSHOT_PATH" > /dev/null && \
                 echo "Snapshot $SNAPSHOT_PATH deleted."
